<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_message_pincode</name>
   <tag></tag>
   <elementGuidId>3e4f9dff-fefa-447c-b352-269d2985d668</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-error[@id='mat-mdc-error-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-mdc-error-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-error</value>
      <webElementGuid>9d351689-13c8-4dc7-8d10-0d06966726cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>86d9b63d-ca7a-465f-96e7-15568dcfe3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-form-field-error mat-mdc-form-field-bottom-align ng-tns-c508571215-6 ng-star-inserted</value>
      <webElementGuid>b60c892b-9acf-4da2-a17f-4a22d3ae4a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>57d0e65a-f7ef-4f3d-9c9d-28a9008458e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-mdc-error-0</value>
      <webElementGuid>159530ea-c4bf-4b95-85cf-e2059231b20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pincode must have 6 digits only and cannot start with 0 </value>
      <webElementGuid>84ed4e17-3a61-4c07-ac63-f1a13d3a5703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-error-0&quot;)</value>
      <webElementGuid>571c8869-8e0d-490d-9c82-e0c7777eb2c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-error[@id='mat-mdc-error-0']</value>
      <webElementGuid>5c40fa77-7c55-476a-a14b-67481a10fa69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pincode'])[1]/following::mat-error[1]</value>
      <webElementGuid>a9eb0974-782f-4f75-9ac6-6c9e4f8852ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Line 2'])[1]/following::mat-error[1]</value>
      <webElementGuid>e6eee6f5-68ef-4469-9ce5-e1f6f66f30e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>811e809d-7fb6-47ba-bed3-63a4dc81b449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Place Order'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>465149cc-3ff8-45a0-be76-521a8ece5556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pincode must have 6 digits only and cannot start with 0']/parent::*</value>
      <webElementGuid>0d2d43a0-9fe1-48a5-a2e1-e8409bd09286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-error</value>
      <webElementGuid>b827d434-064a-403c-a8a9-b169db19f2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-error[@id = 'mat-mdc-error-0' and (text() = ' Pincode must have 6 digits only and cannot start with 0 ' or . = ' Pincode must have 6 digits only and cannot start with 0 ')]</value>
      <webElementGuid>1ee188bc-5c43-45ee-b137-7acc84dccef0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
